"""The hub's raw events move into daily range partitions on `at`, so retention drops a day whole.

Postgres needs the partition key in every primary key and unique constraint, so `starpulse_events` is keyed on
`(id, at)` and unique on `(event_id, at)`. An event keeps one `at` however often it is delivered, so a replay still
lands on the same pair. Rows the table already holds are copied into partitions for the days they span.

Revision ID: 0002
Revises: 0001
"""

from datetime import UTC, datetime, timedelta

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"

_DAY = 86400


def _name(day: datetime) -> str:
    return f"starpulse_events_{day:%Y%m%d}"


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE starpulse_events_partitioned (
            id integer GENERATED BY DEFAULT AS IDENTITY,
            stream varchar NOT NULL,
            event_id varchar NOT NULL,
            fields json NOT NULL,
            at double precision NOT NULL,
            PRIMARY KEY (id, at),
            UNIQUE (event_id, at)
        ) PARTITION BY RANGE (at)
        """
    )
    bounds = op.get_bind().execute(sa.text("SELECT min(at), max(at) FROM starpulse_events")).one()
    if bounds[0] is not None:
        day = datetime.fromtimestamp(bounds[0], UTC).replace(hour=0, minute=0, second=0, microsecond=0)
        while day.timestamp() <= bounds[1]:
            start = int(day.timestamp())
            op.execute(
                f"CREATE TABLE {_name(day)} PARTITION OF starpulse_events_partitioned "
                f"FOR VALUES FROM ({start}) TO ({start + _DAY})"
            )
            day += timedelta(days=1)
    op.execute(
        "INSERT INTO starpulse_events_partitioned (id, stream, event_id, fields, at) "
        "OVERRIDING SYSTEM VALUE SELECT id, stream, event_id, fields, at FROM starpulse_events"
    )
    op.drop_table("starpulse_events")
    op.execute("ALTER TABLE starpulse_events_partitioned RENAME TO starpulse_events")
    op.execute(
        "SELECT setval(pg_get_serial_sequence('starpulse_events', 'id'), coalesce(max(id), 1), count(*) > 0) "
        "FROM starpulse_events"
    )
    op.create_index("ix_starpulse_events_stream", "starpulse_events", ["stream", "id"])
    op.create_index("ix_starpulse_events_at", "starpulse_events", ["at"])
